# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/resources/calibration_interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalibWindow(object):
    def setupUi(self, CalibWindow):
        CalibWindow.setObjectName("CalibWindow")
        CalibWindow.resize(815, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalibWindow.sizePolicy().hasHeightForWidth())
        CalibWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(CalibWindow)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_coarse = QtWidgets.QGroupBox(CalibWindow)
        self.groupBox_coarse.setObjectName("groupBox_coarse")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_coarse)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_coarse)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cBoxRefDev = QtWidgets.QComboBox(self.groupBox_5)
        self.cBoxRefDev.setObjectName("cBoxRefDev")
        self.verticalLayout_5.addWidget(self.cBoxRefDev)
        self.ref_dev_connect = QtWidgets.QPushButton(self.groupBox_5)
        self.ref_dev_connect.setObjectName("ref_dev_connect")
        self.verticalLayout_5.addWidget(self.ref_dev_connect)
        self.horizontalLayout_4.addLayout(self.verticalLayout_5)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setMinimumSize(QtCore.QSize(100, 120))
        self.groupBox_4.setObjectName("groupBox_4")
        self.ref_dev_channel2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.ref_dev_channel2.setEnabled(False)
        self.ref_dev_channel2.setGeometry(QtCore.QRect(20, 70, 100, 17))
        self.ref_dev_channel2.setObjectName("ref_dev_channel2")
        self.ref_dev_channel3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.ref_dev_channel3.setEnabled(False)
        self.ref_dev_channel3.setGeometry(QtCore.QRect(20, 90, 100, 17))
        self.ref_dev_channel3.setObjectName("ref_dev_channel3")
        self.ref_dev_channel1 = QtWidgets.QRadioButton(self.groupBox_4)
        self.ref_dev_channel1.setEnabled(False)
        self.ref_dev_channel1.setGeometry(QtCore.QRect(20, 50, 100, 17))
        self.ref_dev_channel1.setObjectName("ref_dev_channel1")
        self.ref_dev_channel0 = QtWidgets.QRadioButton(self.groupBox_4)
        self.ref_dev_channel0.setEnabled(False)
        self.ref_dev_channel0.setGeometry(QtCore.QRect(20, 30, 100, 17))
        self.ref_dev_channel0.setObjectName("ref_dev_channel0")
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName("groupBox_6")
        self.ref_dev_impedance0 = QtWidgets.QRadioButton(self.groupBox_6)
        self.ref_dev_impedance0.setEnabled(False)
        self.ref_dev_impedance0.setGeometry(QtCore.QRect(20, 30, 100, 13))
        self.ref_dev_impedance0.setText("")
        self.ref_dev_impedance0.setObjectName("ref_dev_impedance0")
        self.ref_dev_impedance2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.ref_dev_impedance2.setEnabled(False)
        self.ref_dev_impedance2.setGeometry(QtCore.QRect(20, 70, 100, 13))
        self.ref_dev_impedance2.setText("")
        self.ref_dev_impedance2.setObjectName("ref_dev_impedance2")
        self.ref_dev_impedance1 = QtWidgets.QRadioButton(self.groupBox_6)
        self.ref_dev_impedance1.setEnabled(False)
        self.ref_dev_impedance1.setGeometry(QtCore.QRect(20, 50, 100, 13))
        self.ref_dev_impedance1.setText("")
        self.ref_dev_impedance1.setObjectName("ref_dev_impedance1")
        self.ref_dev_impedance3 = QtWidgets.QRadioButton(self.groupBox_6)
        self.ref_dev_impedance3.setEnabled(False)
        self.ref_dev_impedance3.setGeometry(QtCore.QRect(20, 90, 100, 13))
        self.ref_dev_impedance3.setText("")
        self.ref_dev_impedance3.setObjectName("ref_dev_impedance3")
        self.horizontalLayout_4.addWidget(self.groupBox_6)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_start_coarse = QtWidgets.QPushButton(self.groupBox_coarse)
        self.button_start_coarse.setObjectName("button_start_coarse")
        self.horizontalLayout_5.addWidget(self.button_start_coarse)
        self.button_stop_coarse = QtWidgets.QPushButton(self.groupBox_coarse)
        self.button_stop_coarse.setObjectName("button_stop_coarse")
        self.horizontalLayout_5.addWidget(self.button_stop_coarse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_calib_const = QtWidgets.QLabel(self.groupBox_coarse)
        self.label_calib_const.setObjectName("label_calib_const")
        self.horizontalLayout_6.addWidget(self.label_calib_const)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_coarse_mess = QtWidgets.QLabel(self.groupBox_coarse)
        self.label_coarse_mess.setObjectName("label_coarse_mess")
        self.verticalLayout_2.addWidget(self.label_coarse_mess)
        self.plotVLayout_coarse = QtWidgets.QVBoxLayout()
        self.plotVLayout_coarse.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotVLayout_coarse.setObjectName("plotVLayout_coarse")
        self.verticalLayout_2.addLayout(self.plotVLayout_coarse)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8.addWidget(self.groupBox_coarse)
        self.groupBox_fine = QtWidgets.QGroupBox(CalibWindow)
        self.groupBox_fine.setObjectName("groupBox_fine")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_fine)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_start_fine = QtWidgets.QPushButton(self.groupBox_fine)
        self.button_start_fine.setObjectName("button_start_fine")
        self.horizontalLayout_7.addWidget(self.button_start_fine)
        self.button_stop_fine = QtWidgets.QPushButton(self.groupBox_fine)
        self.button_stop_fine.setObjectName("button_stop_fine")
        self.horizontalLayout_7.addWidget(self.button_stop_fine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label_fine_mess = QtWidgets.QLabel(self.groupBox_fine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fine_mess.sizePolicy().hasHeightForWidth())
        self.label_fine_mess.setSizePolicy(sizePolicy)
        self.label_fine_mess.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_fine_mess.setObjectName("label_fine_mess")
        self.verticalLayout_3.addWidget(self.label_fine_mess)
        self.plotVLayout_fine = QtWidgets.QVBoxLayout()
        self.plotVLayout_fine.setObjectName("plotVLayout_fine")
        self.verticalLayout_3.addLayout(self.plotVLayout_fine)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_fine)
        self.gridLayout.addLayout(self.horizontalLayout_8, 2, 1, 1, 1)
        self.ErrorLabel = QtWidgets.QLabel(CalibWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ErrorLabel.sizePolicy().hasHeightForWidth())
        self.ErrorLabel.setSizePolicy(sizePolicy)
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.gridLayout.addWidget(self.ErrorLabel, 4, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(CalibWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(CalibWindow)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cBoxTargetDev = QtWidgets.QComboBox(self.groupBox_3)
        self.cBoxTargetDev.setObjectName("cBoxTargetDev")
        self.verticalLayout.addWidget(self.cBoxTargetDev)
        self.target_dev_connect = QtWidgets.QPushButton(self.groupBox_3)
        self.target_dev_connect.setMinimumSize(QtCore.QSize(120, 0))
        self.target_dev_connect.setObjectName("target_dev_connect")
        self.verticalLayout.addWidget(self.target_dev_connect)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setMinimumSize(QtCore.QSize(120, 120))
        self.groupBox.setObjectName("groupBox")
        self.target_dev_channel0 = QtWidgets.QRadioButton(self.groupBox)
        self.target_dev_channel0.setEnabled(False)
        self.target_dev_channel0.setGeometry(QtCore.QRect(20, 30, 100, 17))
        self.target_dev_channel0.setObjectName("target_dev_channel0")
        self.target_dev_channel2 = QtWidgets.QRadioButton(self.groupBox)
        self.target_dev_channel2.setEnabled(False)
        self.target_dev_channel2.setGeometry(QtCore.QRect(20, 70, 100, 17))
        self.target_dev_channel2.setObjectName("target_dev_channel2")
        self.target_dev_channel3 = QtWidgets.QRadioButton(self.groupBox)
        self.target_dev_channel3.setEnabled(False)
        self.target_dev_channel3.setGeometry(QtCore.QRect(20, 90, 100, 17))
        self.target_dev_channel3.setObjectName("target_dev_channel3")
        self.target_dev_channel1 = QtWidgets.QRadioButton(self.groupBox)
        self.target_dev_channel1.setEnabled(False)
        self.target_dev_channel1.setGeometry(QtCore.QRect(20, 50, 100, 17))
        self.target_dev_channel1.setObjectName("target_dev_channel1")
        self.horizontalLayout_10.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_2.setEnabled(False)
        self.groupBox_2.setMinimumSize(QtCore.QSize(120, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.target_dev_impedance0 = QtWidgets.QRadioButton(self.groupBox_2)
        self.target_dev_impedance0.setEnabled(False)
        self.target_dev_impedance0.setGeometry(QtCore.QRect(20, 30, 100, 13))
        self.target_dev_impedance0.setText("")
        self.target_dev_impedance0.setObjectName("target_dev_impedance0")
        self.target_dev_impedance3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.target_dev_impedance3.setEnabled(False)
        self.target_dev_impedance3.setGeometry(QtCore.QRect(20, 90, 100, 13))
        self.target_dev_impedance3.setText("")
        self.target_dev_impedance3.setObjectName("target_dev_impedance3")
        self.target_dev_impedance2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.target_dev_impedance2.setGeometry(QtCore.QRect(20, 70, 100, 13))
        self.target_dev_impedance2.setText("")
        self.target_dev_impedance2.setObjectName("target_dev_impedance2")
        self.target_dev_impedance1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.target_dev_impedance1.setEnabled(False)
        self.target_dev_impedance1.setGeometry(QtCore.QRect(20, 50, 100, 13))
        self.target_dev_impedance1.setText("")
        self.target_dev_impedance1.setObjectName("target_dev_impedance1")
        self.horizontalLayout_10.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)

        self.retranslateUi(CalibWindow)
        QtCore.QMetaObject.connectSlotsByName(CalibWindow)

    def retranslateUi(self, CalibWindow):
        _translate = QtCore.QCoreApplication.translate
        CalibWindow.setWindowTitle(_translate("CalibWindow", "FPGA Frequency Meter Calibration"))
        self.groupBox_coarse.setTitle(_translate("CalibWindow", "Coarse Calibration"))
        self.groupBox_5.setTitle(_translate("CalibWindow", "Reference device"))
        self.ref_dev_connect.setText(_translate("CalibWindow", "Connect"))
        self.groupBox_4.setTitle(_translate("CalibWindow", "Channels"))
        self.ref_dev_channel2.setText(_translate("CalibWindow", "3"))
        self.ref_dev_channel3.setText(_translate("CalibWindow", "4"))
        self.ref_dev_channel1.setText(_translate("CalibWindow", "2"))
        self.ref_dev_channel0.setText(_translate("CalibWindow", "1"))
        self.groupBox_6.setTitle(_translate("CalibWindow", "Impedance"))
        self.button_start_coarse.setText(_translate("CalibWindow", "Start"))
        self.button_stop_coarse.setText(_translate("CalibWindow", "Stop"))
        self.label_calib_const.setText(_translate("CalibWindow", "Coarse calibration constant:"))
        self.label_coarse_mess.setText(_translate("CalibWindow", "Coarse Calibration Messages"))
        self.groupBox_fine.setTitle(_translate("CalibWindow", "Fine Calibration"))
        self.button_start_fine.setText(_translate("CalibWindow", "Start"))
        self.button_stop_fine.setText(_translate("CalibWindow", "Stop"))
        self.label_fine_mess.setText(_translate("CalibWindow", "Fine Calibration Messages"))
        self.groupBox_3.setTitle(_translate("CalibWindow", "Target device (to be calibrated)"))
        self.target_dev_connect.setText(_translate("CalibWindow", "Connect"))
        self.groupBox.setTitle(_translate("CalibWindow", "Channels"))
        self.target_dev_channel0.setText(_translate("CalibWindow", "1"))
        self.target_dev_channel2.setText(_translate("CalibWindow", "3"))
        self.target_dev_channel3.setText(_translate("CalibWindow", "4"))
        self.target_dev_channel1.setText(_translate("CalibWindow", "2"))
        self.groupBox_2.setTitle(_translate("CalibWindow", "Impedance"))

