# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/resources/calibration_interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CalibWindow(object):
    def setupUi(self, CalibWindow):
        CalibWindow.setObjectName("CalibWindow")
        CalibWindow.resize(789, 653)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalibWindow.sizePolicy().hasHeightForWidth())
        CalibWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(CalibWindow)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox_coarse = QtWidgets.QGroupBox(CalibWindow)
        self.groupBox_coarse.setObjectName("groupBox_coarse")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_coarse)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox_coarse)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.comboBoxRefDev = QtWidgets.QComboBox(self.groupBox_coarse)
        self.comboBoxRefDev.setObjectName("comboBoxRefDev")
        self.horizontalLayout_4.addWidget(self.comboBoxRefDev)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_start_coarse = QtWidgets.QPushButton(self.groupBox_coarse)
        self.button_start_coarse.setObjectName("button_start_coarse")
        self.horizontalLayout_5.addWidget(self.button_start_coarse)
        self.button_stop_coarse = QtWidgets.QPushButton(self.groupBox_coarse)
        self.button_stop_coarse.setObjectName("button_stop_coarse")
        self.horizontalLayout_5.addWidget(self.button_stop_coarse)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_calib_const = QtWidgets.QLabel(self.groupBox_coarse)
        self.label_calib_const.setObjectName("label_calib_const")
        self.horizontalLayout_6.addWidget(self.label_calib_const)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label_coarse_mess = QtWidgets.QLabel(self.groupBox_coarse)
        self.label_coarse_mess.setObjectName("label_coarse_mess")
        self.verticalLayout_2.addWidget(self.label_coarse_mess)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.plotVLayout_coarse = QtWidgets.QVBoxLayout()
        self.plotVLayout_coarse.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.plotVLayout_coarse.setObjectName("plotVLayout_coarse")
        self.verticalLayout_2.addLayout(self.plotVLayout_coarse)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_8.addWidget(self.groupBox_coarse)
        self.groupBox_fine = QtWidgets.QGroupBox(CalibWindow)
        self.groupBox_fine.setObjectName("groupBox_fine")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_fine)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_start_fine = QtWidgets.QPushButton(self.groupBox_fine)
        self.button_start_fine.setObjectName("button_start_fine")
        self.horizontalLayout_7.addWidget(self.button_start_fine)
        self.button_stop_fine = QtWidgets.QPushButton(self.groupBox_fine)
        self.button_stop_fine.setObjectName("button_stop_fine")
        self.horizontalLayout_7.addWidget(self.button_stop_fine)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label_fine_mess = QtWidgets.QLabel(self.groupBox_fine)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_fine_mess.sizePolicy().hasHeightForWidth())
        self.label_fine_mess.setSizePolicy(sizePolicy)
        self.label_fine_mess.setObjectName("label_fine_mess")
        self.verticalLayout_3.addWidget(self.label_fine_mess)
        self.plotVLayout_fine = QtWidgets.QVBoxLayout()
        self.plotVLayout_fine.setObjectName("plotVLayout_fine")
        self.verticalLayout_3.addLayout(self.plotVLayout_fine)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8.addWidget(self.groupBox_fine)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CalibWindow)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.ErrorLabel = QtWidgets.QLabel(CalibWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ErrorLabel.sizePolicy().hasHeightForWidth())
        self.ErrorLabel.setSizePolicy(sizePolicy)
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.gridLayout.addWidget(self.ErrorLabel, 3, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(CalibWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.comboBoxDevToCalib = QtWidgets.QComboBox(CalibWindow)
        self.comboBoxDevToCalib.setObjectName("comboBoxDevToCalib")
        self.horizontalLayout_3.addWidget(self.comboBoxDevToCalib)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)

        self.retranslateUi(CalibWindow)
        QtCore.QMetaObject.connectSlotsByName(CalibWindow)

    def retranslateUi(self, CalibWindow):
        _translate = QtCore.QCoreApplication.translate
        CalibWindow.setWindowTitle(_translate("CalibWindow", "FPGA Frequency Meter Calibration"))
        self.groupBox_coarse.setTitle(_translate("CalibWindow", "Coarse Calibration"))
        self.label.setText(_translate("CalibWindow", "Reference device"))
        self.button_start_coarse.setText(_translate("CalibWindow", "Start"))
        self.button_stop_coarse.setText(_translate("CalibWindow", "Stop"))
        self.label_calib_const.setText(_translate("CalibWindow", "Coarse calibration constant:"))
        self.label_coarse_mess.setText(_translate("CalibWindow", "Coarse Calibration Messages"))
        self.groupBox_fine.setTitle(_translate("CalibWindow", "Fine Calibration"))
        self.button_start_fine.setText(_translate("CalibWindow", "Start"))
        self.button_stop_fine.setText(_translate("CalibWindow", "Stop"))
        self.label_fine_mess.setText(_translate("CalibWindow", "Fine Calibration Messages"))
        self.label_3.setText(_translate("CalibWindow", "Device to be calibrated:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalibWindow = QtWidgets.QDialog()
    ui = Ui_CalibWindow()
    ui.setupUi(CalibWindow)
    CalibWindow.show()
    sys.exit(app.exec_())

