# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/resources/device_interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DevManagerWindow(object):
    def setupUi(self, DevManagerWindow):
        DevManagerWindow.setObjectName(_fromUtf8("DevManagerWindow"))
        DevManagerWindow.resize(670, 518)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DevManagerWindow.sizePolicy().hasHeightForWidth())
        DevManagerWindow.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(DevManagerWindow)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ErrorLabel = QtGui.QLabel(DevManagerWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ErrorLabel.sizePolicy().hasHeightForWidth())
        self.ErrorLabel.setSizePolicy(sizePolicy)
        self.ErrorLabel.setText(_fromUtf8(""))
        self.ErrorLabel.setObjectName(_fromUtf8("ErrorLabel"))
        self.gridLayout.addWidget(self.ErrorLabel, 5, 0, 1, 3)
        self.GeneralPropertiesgroupBox = QtGui.QGroupBox(DevManagerWindow)
        self.GeneralPropertiesgroupBox.setObjectName(_fromUtf8("GeneralPropertiesgroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.GeneralPropertiesgroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_2 = QtGui.QLabel(self.GeneralPropertiesgroupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.GeneralPropertiesgroupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.GeneralPropertiesgroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.GeneralPropertiesgroupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.label = QtGui.QLabel(self.GeneralPropertiesgroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.DevNameText = QtGui.QLineEdit(self.GeneralPropertiesgroupBox)
        self.DevNameText.setObjectName(_fromUtf8("DevNameText"))
        self.gridLayout_2.addWidget(self.DevNameText, 0, 1, 1, 1)
        self.DevVendorText = QtGui.QLineEdit(self.GeneralPropertiesgroupBox)
        self.DevVendorText.setObjectName(_fromUtf8("DevVendorText"))
        self.gridLayout_2.addWidget(self.DevVendorText, 1, 1, 1, 1)
        self.DevModelText = QtGui.QLineEdit(self.GeneralPropertiesgroupBox)
        self.DevModelText.setObjectName(_fromUtf8("DevModelText"))
        self.gridLayout_2.addWidget(self.DevModelText, 2, 1, 1, 1)
        self.DevSerialNText = QtGui.QLineEdit(self.GeneralPropertiesgroupBox)
        self.DevSerialNText.setObjectName(_fromUtf8("DevSerialNText"))
        self.gridLayout_2.addWidget(self.DevSerialNText, 3, 1, 1, 1)
        self.DevFirmVersionText = QtGui.QLineEdit(self.GeneralPropertiesgroupBox)
        self.DevFirmVersionText.setObjectName(_fromUtf8("DevFirmVersionText"))
        self.gridLayout_2.addWidget(self.DevFirmVersionText, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.GeneralPropertiesgroupBox, 1, 0, 3, 1)
        self.groupBox = QtGui.QGroupBox(DevManagerWindow)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.NChannelsBox = QtGui.QSpinBox(self.groupBox)
        self.NChannelsBox.setMinimum(1)
        self.NChannelsBox.setObjectName(_fromUtf8("NChannelsBox"))
        self.gridLayout_5.addWidget(self.NChannelsBox, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.NSignalsBox = QtGui.QSpinBox(self.groupBox)
        self.NSignalsBox.setMinimum(1)
        self.NSignalsBox.setMaximum(4)
        self.NSignalsBox.setObjectName(_fromUtf8("NSignalsBox"))
        self.gridLayout_5.addWidget(self.NSignalsBox, 1, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.S2label = QtGui.QLabel(self.groupBox_2)
        self.S2label.setEnabled(False)
        self.S2label.setObjectName(_fromUtf8("S2label"))
        self.gridLayout_6.addWidget(self.S2label, 0, 3, 1, 1)
        self.S3label = QtGui.QLabel(self.groupBox_2)
        self.S3label.setEnabled(False)
        self.S3label.setObjectName(_fromUtf8("S3label"))
        self.gridLayout_6.addWidget(self.S3label, 1, 0, 1, 1)
        self.S4label = QtGui.QLabel(self.groupBox_2)
        self.S4label.setEnabled(False)
        self.S4label.setObjectName(_fromUtf8("S4label"))
        self.gridLayout_6.addWidget(self.S4label, 1, 3, 1, 1)
        self.S3comboBox = QtGui.QComboBox(self.groupBox_2)
        self.S3comboBox.setEnabled(False)
        self.S3comboBox.setObjectName(_fromUtf8("S3comboBox"))
        self.S3comboBox.addItem(_fromUtf8(""))
        self.S3comboBox.addItem(_fromUtf8(""))
        self.S3comboBox.addItem(_fromUtf8(""))
        self.S3comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.S3comboBox, 1, 1, 1, 1)
        self.S2comboBox = QtGui.QComboBox(self.groupBox_2)
        self.S2comboBox.setEnabled(False)
        self.S2comboBox.setObjectName(_fromUtf8("S2comboBox"))
        self.S2comboBox.addItem(_fromUtf8(""))
        self.S2comboBox.addItem(_fromUtf8(""))
        self.S2comboBox.addItem(_fromUtf8(""))
        self.S2comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.S2comboBox, 0, 4, 1, 1)
        self.S1comboBox = QtGui.QComboBox(self.groupBox_2)
        self.S1comboBox.setObjectName(_fromUtf8("S1comboBox"))
        self.S1comboBox.addItem(_fromUtf8(""))
        self.S1comboBox.addItem(_fromUtf8(""))
        self.S1comboBox.addItem(_fromUtf8(""))
        self.S1comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.S1comboBox, 0, 1, 1, 1)
        self.S1label = QtGui.QLabel(self.groupBox_2)
        self.S1label.setObjectName(_fromUtf8("S1label"))
        self.gridLayout_6.addWidget(self.S1label, 0, 0, 1, 1)
        self.S4comboBox = QtGui.QComboBox(self.groupBox_2)
        self.S4comboBox.setEnabled(False)
        self.S4comboBox.setObjectName(_fromUtf8("S4comboBox"))
        self.S4comboBox.addItem(_fromUtf8(""))
        self.S4comboBox.addItem(_fromUtf8(""))
        self.S4comboBox.addItem(_fromUtf8(""))
        self.S4comboBox.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.S4comboBox, 1, 4, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 1)
        self.line = QtGui.QFrame(DevManagerWindow)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 1, 1, 4, 1)
        self.groupBox_3 = QtGui.QGroupBox(DevManagerWindow)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.MegaOhmcheckBox = QtGui.QCheckBox(self.groupBox_3)
        self.MegaOhmcheckBox.setObjectName(_fromUtf8("MegaOhmcheckBox"))
        self.gridLayout_7.addWidget(self.MegaOhmcheckBox, 0, 1, 1, 1)
        self.Ohm50checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.Ohm50checkBox.setObjectName(_fromUtf8("Ohm50checkBox"))
        self.gridLayout_7.addWidget(self.Ohm50checkBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 4, 2, 1, 1)
        self.CommSettingsgroupBox_2 = QtGui.QGroupBox(DevManagerWindow)
        self.CommSettingsgroupBox_2.setObjectName(_fromUtf8("CommSettingsgroupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.CommSettingsgroupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.CommSettingsgroupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.CommProtocolBox = QtGui.QComboBox(self.CommSettingsgroupBox_2)
        self.CommProtocolBox.setObjectName(_fromUtf8("CommProtocolBox"))
        self.CommProtocolBox.addItem(_fromUtf8(""))
        self.CommProtocolBox.addItem(_fromUtf8(""))
        self.CommProtocolBox.addItem(_fromUtf8(""))
        self.CommProtocolBox.addItem(_fromUtf8(""))
        self.CommProtocolBox.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.CommProtocolBox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.CommSettingsgroupBox_2, 1, 2, 1, 1)
        self.CommPropertiesgroupBox = QtGui.QGroupBox(DevManagerWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CommPropertiesgroupBox.sizePolicy().hasHeightForWidth())
        self.CommPropertiesgroupBox.setSizePolicy(sizePolicy)
        self.CommPropertiesgroupBox.setObjectName(_fromUtf8("CommPropertiesgroupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.CommPropertiesgroupBox)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.CommLabel_1 = QtGui.QLabel(self.CommPropertiesgroupBox)
        self.CommLabel_1.setObjectName(_fromUtf8("CommLabel_1"))
        self.gridLayout_3.addWidget(self.CommLabel_1, 1, 0, 1, 1)
        self.CommText_1 = QtGui.QLineEdit(self.CommPropertiesgroupBox)
        self.CommText_1.setObjectName(_fromUtf8("CommText_1"))
        self.gridLayout_3.addWidget(self.CommText_1, 1, 1, 1, 1)
        self.CommText_2 = QtGui.QLineEdit(self.CommPropertiesgroupBox)
        self.CommText_2.setObjectName(_fromUtf8("CommText_2"))
        self.gridLayout_3.addWidget(self.CommText_2, 2, 1, 1, 1)
        self.CommLabel_2 = QtGui.QLabel(self.CommPropertiesgroupBox)
        self.CommLabel_2.setObjectName(_fromUtf8("CommLabel_2"))
        self.gridLayout_3.addWidget(self.CommLabel_2, 2, 0, 1, 1)
        self.CommLabel_3 = QtGui.QLabel(self.CommPropertiesgroupBox)
        self.CommLabel_3.setObjectName(_fromUtf8("CommLabel_3"))
        self.gridLayout_3.addWidget(self.CommLabel_3, 3, 0, 1, 1)
        self.CommText_3 = QtGui.QLineEdit(self.CommPropertiesgroupBox)
        self.CommText_3.setObjectName(_fromUtf8("CommText_3"))
        self.gridLayout_3.addWidget(self.CommText_3, 3, 1, 1, 1)
        self.CommLabel_4 = QtGui.QLabel(self.CommPropertiesgroupBox)
        self.CommLabel_4.setObjectName(_fromUtf8("CommLabel_4"))
        self.gridLayout_3.addWidget(self.CommLabel_4, 4, 0, 1, 1)
        self.CommText_4 = QtGui.QLineEdit(self.CommPropertiesgroupBox)
        self.CommText_4.setObjectName(_fromUtf8("CommText_4"))
        self.gridLayout_3.addWidget(self.CommText_4, 4, 1, 1, 1)
        self.gridLayout.addWidget(self.CommPropertiesgroupBox, 2, 2, 2, 1)
        self.buttonBox = QtGui.QDialogButtonBox(DevManagerWindow)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Open|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 6, 2, 1, 1)

        self.retranslateUi(DevManagerWindow)
        QtCore.QMetaObject.connectSlotsByName(DevManagerWindow)

    def retranslateUi(self, DevManagerWindow):
        DevManagerWindow.setWindowTitle(_translate("DevManagerWindow", "Device manager", None))
        self.GeneralPropertiesgroupBox.setTitle(_translate("DevManagerWindow", "General properties", None))
        self.label_2.setText(_translate("DevManagerWindow", "Vendor:", None))
        self.label_3.setText(_translate("DevManagerWindow", "Model:", None))
        self.label_4.setText(_translate("DevManagerWindow", "Serial Nº:", None))
        self.label_7.setText(_translate("DevManagerWindow", "Firmware version:", None))
        self.label.setText(_translate("DevManagerWindow", "Name:", None))
        self.groupBox.setTitle(_translate("DevManagerWindow", "Chanels properties", None))
        self.label_6.setText(_translate("DevManagerWindow", "Signals per ch.: ", None))
        self.label_5.setText(_translate("DevManagerWindow", "Nº of chanels:", None))
        self.groupBox_2.setTitle(_translate("DevManagerWindow", "Signal types", None))
        self.S2label.setText(_translate("DevManagerWindow", "Signal 2:", None))
        self.S3label.setText(_translate("DevManagerWindow", "Signal 3:", None))
        self.S4label.setText(_translate("DevManagerWindow", "Signal 4:", None))
        self.S3comboBox.setItemText(0, _translate("DevManagerWindow", "<None>", None))
        self.S3comboBox.setItemText(1, _translate("DevManagerWindow", "Fine", None))
        self.S3comboBox.setItemText(2, _translate("DevManagerWindow", "Fine-CDT", None))
        self.S3comboBox.setItemText(3, _translate("DevManagerWindow", "Coarse", None))
        self.S2comboBox.setItemText(0, _translate("DevManagerWindow", "<None>", None))
        self.S2comboBox.setItemText(1, _translate("DevManagerWindow", "Fine", None))
        self.S2comboBox.setItemText(2, _translate("DevManagerWindow", "Fine-CDT", None))
        self.S2comboBox.setItemText(3, _translate("DevManagerWindow", "Coarse", None))
        self.S1comboBox.setItemText(0, _translate("DevManagerWindow", "<None>", None))
        self.S1comboBox.setItemText(1, _translate("DevManagerWindow", "Fine", None))
        self.S1comboBox.setItemText(2, _translate("DevManagerWindow", "Fine-CDT", None))
        self.S1comboBox.setItemText(3, _translate("DevManagerWindow", "Coarse", None))
        self.S1label.setText(_translate("DevManagerWindow", "Signal 1:", None))
        self.S4comboBox.setItemText(0, _translate("DevManagerWindow", "<None>", None))
        self.S4comboBox.setItemText(1, _translate("DevManagerWindow", "Fine", None))
        self.S4comboBox.setItemText(2, _translate("DevManagerWindow", "Fine-CDT", None))
        self.S4comboBox.setItemText(3, _translate("DevManagerWindow", "Coarse", None))
        self.groupBox_3.setTitle(_translate("DevManagerWindow", "Available impedances", None))
        self.MegaOhmcheckBox.setText(_translate("DevManagerWindow", "1 MΩ", None))
        self.Ohm50checkBox.setText(_translate("DevManagerWindow", "50 Ω", None))
        self.CommSettingsgroupBox_2.setTitle(_translate("DevManagerWindow", "Communication settings", None))
        self.label_8.setText(_translate("DevManagerWindow", "Protocol", None))
        self.CommProtocolBox.setItemText(0, _translate("DevManagerWindow", "<None>", None))
        self.CommProtocolBox.setItemText(1, _translate("DevManagerWindow", "TCP/IP", None))
        self.CommProtocolBox.setItemText(2, _translate("DevManagerWindow", "Serial", None))
        self.CommProtocolBox.setItemText(3, _translate("DevManagerWindow", "USB", None))
        self.CommProtocolBox.setItemText(4, _translate("DevManagerWindow", "VISA", None))
        self.CommPropertiesgroupBox.setTitle(_translate("DevManagerWindow", "Communication properties", None))
        self.CommLabel_1.setText(_translate("DevManagerWindow", "Prop1:", None))
        self.CommLabel_2.setText(_translate("DevManagerWindow", "Prop2:", None))
        self.CommLabel_3.setText(_translate("DevManagerWindow", "Prop3:", None))
        self.CommLabel_4.setText(_translate("DevManagerWindow", "Prop4:", None))

