# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/resources/interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(902, 554)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.LoggerBrowser = QtGui.QTextBrowser(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LoggerBrowser.setFont(font)
        self.LoggerBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LoggerBrowser.setAutoFillBackground(False)
        self.LoggerBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.LoggerBrowser.setObjectName(_fromUtf8("LoggerBrowser"))
        self.gridLayout_3.addWidget(self.LoggerBrowser, 2, 0, 2, 5)
        spacerItem = QtGui.QSpacerItem(80, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.InfoCheck = QtGui.QRadioButton(self.groupBox)
        self.InfoCheck.setChecked(True)
        self.InfoCheck.setAutoExclusive(False)
        self.InfoCheck.setObjectName(_fromUtf8("InfoCheck"))
        self.gridLayout_3.addWidget(self.InfoCheck, 1, 0, 1, 1)
        self.ErrorCheck = QtGui.QRadioButton(self.groupBox)
        self.ErrorCheck.setChecked(True)
        self.ErrorCheck.setAutoExclusive(False)
        self.ErrorCheck.setObjectName(_fromUtf8("ErrorCheck"))
        self.gridLayout_3.addWidget(self.ErrorCheck, 1, 2, 1, 1)
        self.DebugCheck = QtGui.QRadioButton(self.groupBox)
        self.DebugCheck.setEnabled(True)
        self.DebugCheck.setAutoExclusive(False)
        self.DebugCheck.setObjectName(_fromUtf8("DebugCheck"))
        self.gridLayout_3.addWidget(self.DebugCheck, 1, 3, 1, 1)
        self.WarnCheck = QtGui.QRadioButton(self.groupBox)
        self.WarnCheck.setChecked(True)
        self.WarnCheck.setAutoExclusive(False)
        self.WarnCheck.setObjectName(_fromUtf8("WarnCheck"))
        self.gridLayout_3.addWidget(self.WarnCheck, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 4)
        self.ErrorButton = QtGui.QPushButton(self.centralwidget)
        self.ErrorButton.setObjectName(_fromUtf8("ErrorButton"))
        self.gridLayout.addWidget(self.ErrorButton, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(48, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        self.WarnButton = QtGui.QPushButton(self.centralwidget)
        self.WarnButton.setObjectName(_fromUtf8("WarnButton"))
        self.gridLayout.addWidget(self.WarnButton, 0, 1, 1, 1)
        self.DebugButton = QtGui.QPushButton(self.centralwidget)
        self.DebugButton.setObjectName(_fromUtf8("DebugButton"))
        self.gridLayout.addWidget(self.DebugButton, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 902, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menuBar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuPlugins = QtGui.QMenu(self.menuBar)
        self.menuPlugins.setObjectName(_fromUtf8("menuPlugins"))
        self.menuTools = QtGui.QMenu(self.menuBar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtGui.QAction(MainWindow)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionEdit = QtGui.QAction(MainWindow)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionLoad = QtGui.QAction(MainWindow)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionLog_console = QtGui.QAction(MainWindow)
        self.actionLog_console.setCheckable(True)
        self.actionLog_console.setObjectName(_fromUtf8("actionLog_console"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionFPGA_sensor_callibrator = QtGui.QAction(MainWindow)
        self.actionFPGA_sensor_callibrator.setEnabled(False)
        self.actionFPGA_sensor_callibrator.setObjectName(_fromUtf8("actionFPGA_sensor_callibrator"))
        self.actionDevice_manager = QtGui.QAction(MainWindow)
        self.actionDevice_manager.setCheckable(True)
        self.actionDevice_manager.setObjectName(_fromUtf8("actionDevice_manager"))
        self.actionDevice_Manager = QtGui.QAction(MainWindow)
        self.actionDevice_Manager.setObjectName(_fromUtf8("actionDevice_Manager"))
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionLog_console)
        self.menuView.addAction(self.actionDevice_manager)
        self.menuHelp.addAction(self.actionAbout)
        self.menuPlugins.addAction(self.actionFPGA_sensor_callibrator)
        self.menuTools.addAction(self.actionDevice_Manager)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuPlugins.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Log messages:", None))
        self.InfoCheck.setText(_translate("MainWindow", "Info", None))
        self.ErrorCheck.setText(_translate("MainWindow", "Error", None))
        self.DebugCheck.setText(_translate("MainWindow", "Debug", None))
        self.WarnCheck.setText(_translate("MainWindow", "Warning", None))
        self.ErrorButton.setText(_translate("MainWindow", "ERROR", None))
        self.WarnButton.setText(_translate("MainWindow", "Warning", None))
        self.DebugButton.setText(_translate("MainWindow", "Debug", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuPlugins.setTitle(_translate("MainWindow", "Plugins", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.actionFile.setText(_translate("MainWindow", "File", None))
        self.actionEdit.setText(_translate("MainWindow", "Edit", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionLoad.setText(_translate("MainWindow", "Load", None))
        self.actionExit.setText(_translate("MainWindow", "Quit", None))
        self.actionLog_console.setText(_translate("MainWindow", "Log messages", None))
        self.actionAbout.setText(_translate("MainWindow", "About ...", None))
        self.actionFPGA_sensor_callibrator.setText(_translate("MainWindow", "FPGA sensor callibrator", None))
        self.actionDevice_manager.setText(_translate("MainWindow", "Device manager", None))
        self.actionDevice_Manager.setText(_translate("MainWindow", "Device Manager", None))

