# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/resources/interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 874)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.WarnCheck = QtWidgets.QRadioButton(self.groupBox)
        self.WarnCheck.setChecked(True)
        self.WarnCheck.setAutoExclusive(False)
        self.WarnCheck.setObjectName("WarnCheck")
        self.gridLayout_3.addWidget(self.WarnCheck, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.LoggerBrowser = QtWidgets.QTextBrowser(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LoggerBrowser.setFont(font)
        self.LoggerBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LoggerBrowser.setAutoFillBackground(False)
        self.LoggerBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.LoggerBrowser.setObjectName("LoggerBrowser")
        self.gridLayout_3.addWidget(self.LoggerBrowser, 2, 0, 2, 5)
        self.InfoCheck = QtWidgets.QRadioButton(self.groupBox)
        self.InfoCheck.setChecked(True)
        self.InfoCheck.setAutoExclusive(False)
        self.InfoCheck.setObjectName("InfoCheck")
        self.gridLayout_3.addWidget(self.InfoCheck, 1, 0, 1, 1)
        self.ErrorCheck = QtWidgets.QRadioButton(self.groupBox)
        self.ErrorCheck.setChecked(True)
        self.ErrorCheck.setAutoExclusive(False)
        self.ErrorCheck.setObjectName("ErrorCheck")
        self.gridLayout_3.addWidget(self.ErrorCheck, 1, 2, 1, 1)
        self.DebugCheck = QtWidgets.QRadioButton(self.groupBox)
        self.DebugCheck.setEnabled(True)
        self.DebugCheck.setAutoExclusive(False)
        self.DebugCheck.setObjectName("DebugCheck")
        self.gridLayout_3.addWidget(self.DebugCheck, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        self.measurement_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.measurement_groupBox.setObjectName("measurement_groupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.measurement_groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.TimesgroupBox = QtWidgets.QGroupBox(self.measurement_groupBox)
        self.TimesgroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesgroupBox.sizePolicy().hasHeightForWidth())
        self.TimesgroupBox.setSizePolicy(sizePolicy)
        self.TimesgroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TimesgroupBox.setObjectName("TimesgroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.TimesgroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.FetchTimeBox = QtWidgets.QDoubleSpinBox(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FetchTimeBox.sizePolicy().hasHeightForWidth())
        self.FetchTimeBox.setSizePolicy(sizePolicy)
        self.FetchTimeBox.setAccelerated(True)
        self.FetchTimeBox.setDecimals(3)
        self.FetchTimeBox.setMinimum(0.001)
        self.FetchTimeBox.setMaximum(20.0)
        self.FetchTimeBox.setSingleStep(0.001)
        self.FetchTimeBox.setProperty("value", 1.0)
        self.FetchTimeBox.setObjectName("FetchTimeBox")
        self.horizontalLayout_4.addWidget(self.FetchTimeBox)
        self.label = QtWidgets.QLabel(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SampleTimeBox = QtWidgets.QDoubleSpinBox(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleTimeBox.sizePolicy().hasHeightForWidth())
        self.SampleTimeBox.setSizePolicy(sizePolicy)
        self.SampleTimeBox.setAccelerated(True)
        self.SampleTimeBox.setDecimals(3)
        self.SampleTimeBox.setMinimum(0.001)
        self.SampleTimeBox.setMaximum(20.0)
        self.SampleTimeBox.setSingleStep(0.001)
        self.SampleTimeBox.setProperty("value", 1.0)
        self.SampleTimeBox.setObjectName("SampleTimeBox")
        self.horizontalLayout_5.addWidget(self.SampleTimeBox)
        self.label_2 = QtWidgets.QLabel(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_6.addWidget(self.TimesgroupBox)
        self.StartButton = QtWidgets.QPushButton(self.measurement_groupBox)
        self.StartButton.setMinimumSize(QtCore.QSize(0, 0))
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout_6.addWidget(self.StartButton)
        self.StopButton = QtWidgets.QPushButton(self.measurement_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopButton.sizePolicy().hasHeightForWidth())
        self.StopButton.setSizePolicy(sizePolicy)
        self.StopButton.setMinimumSize(QtCore.QSize(0, 0))
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout_6.addWidget(self.StopButton)
        self.SaveButton = QtWidgets.QPushButton(self.measurement_groupBox)
        self.SaveButton.setObjectName("SaveButton")
        self.verticalLayout_6.addWidget(self.SaveButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.plotControlHLayout = QtWidgets.QHBoxLayout()
        self.plotControlHLayout.setObjectName("plotControlHLayout")
        self.spacer_label = QtWidgets.QLabel(self.measurement_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer_label.sizePolicy().hasHeightForWidth())
        self.spacer_label.setSizePolicy(sizePolicy)
        self.spacer_label.setMinimumSize(QtCore.QSize(140, 0))
        self.spacer_label.setText("")
        self.spacer_label.setObjectName("spacer_label")
        self.plotControlHLayout.addWidget(self.spacer_label)
        self.scrollcheckBox = QtWidgets.QCheckBox(self.measurement_groupBox)
        self.scrollcheckBox.setChecked(True)
        self.scrollcheckBox.setObjectName("scrollcheckBox")
        self.plotControlHLayout.addWidget(self.scrollcheckBox)
        self.label_5 = QtWidgets.QLabel(self.measurement_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.plotControlHLayout.addWidget(self.label_5)
        self.verticalLayout_7.addLayout(self.plotControlHLayout)
        self.plotVLayout = QtWidgets.QVBoxLayout()
        self.plotVLayout.setObjectName("plotVLayout")
        self.verticalLayout_7.addLayout(self.plotVLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.gridLayout.addWidget(self.measurement_groupBox, 0, 0, 3, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.DevLayout = QtWidgets.QHBoxLayout()
        self.DevLayout.setObjectName("DevLayout")
        self.groupBox_dev1 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_dev1.sizePolicy().hasHeightForWidth())
        self.groupBox_dev1.setSizePolicy(sizePolicy)
        self.groupBox_dev1.setObjectName("groupBox_dev1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_dev1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.DeviceComboBox1 = QtWidgets.QComboBox(self.groupBox_dev1)
        self.DeviceComboBox1.setObjectName("DeviceComboBox1")
        self.DeviceComboBox1.addItem("")
        self.DeviceComboBox1.addItem("")
        self.gridLayout_4.addWidget(self.DeviceComboBox1, 0, 0, 1, 1)
        self.ConnectDevButton1 = QtWidgets.QPushButton(self.groupBox_dev1)
        self.ConnectDevButton1.setMinimumSize(QtCore.QSize(90, 0))
        self.ConnectDevButton1.setObjectName("ConnectDevButton1")
        self.gridLayout_4.addWidget(self.ConnectDevButton1, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_dev1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radio_dev1_ch1 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_dev1_ch1.setObjectName("radio_dev1_ch1")
        self.verticalLayout_4.addWidget(self.radio_dev1_ch1)
        self.radio_dev1_ch2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_dev1_ch2.setObjectName("radio_dev1_ch2")
        self.verticalLayout_4.addWidget(self.radio_dev1_ch2)
        self.radio_dev1_ch3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_dev1_ch3.setObjectName("radio_dev1_ch3")
        self.verticalLayout_4.addWidget(self.radio_dev1_ch3)
        self.radio_dev1_ch4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radio_dev1_ch4.setObjectName("radio_dev1_ch4")
        self.verticalLayout_4.addWidget(self.radio_dev1_ch4)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.groupBox_dev1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.dev1_scrollarea = QtWidgets.QScrollArea(self.groupBox_dev1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev1_scrollarea.sizePolicy().hasHeightForWidth())
        self.dev1_scrollarea.setSizePolicy(sizePolicy)
        self.dev1_scrollarea.setMinimumSize(QtCore.QSize(240, 80))
        self.dev1_scrollarea.setWidgetResizable(True)
        self.dev1_scrollarea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dev1_scrollarea.setObjectName("dev1_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 223, 386))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Dev1_Ch1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch1.setObjectName("Dev1_Ch1")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.Dev1_Ch1)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.Dev1_Ch1_S1 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S1.setObjectName("Dev1_Ch1_S1")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S1, 0, 0, 1, 1)
        self.Dev1_Ch1_S2 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S2.setObjectName("Dev1_Ch1_S2")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S2, 0, 1, 1, 1)
        self.Dev1_Ch1_S3 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S3.setObjectName("Dev1_Ch1_S3")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S3, 1, 0, 1, 1)
        self.Dev1_Ch1_S4 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S4.setObjectName("Dev1_Ch1_S4")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch1)
        self.Dev1_Ch2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch2.setObjectName("Dev1_Ch2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.Dev1_Ch2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.Dev1_Ch2_S1 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S1.setObjectName("Dev1_Ch2_S1")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S1, 0, 0, 1, 1)
        self.Dev1_Ch2_S2 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S2.setObjectName("Dev1_Ch2_S2")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S2, 0, 1, 1, 1)
        self.Dev1_Ch2_S3 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S3.setObjectName("Dev1_Ch2_S3")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S3, 1, 0, 1, 1)
        self.Dev1_Ch2_S4 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S4.setObjectName("Dev1_Ch2_S4")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch2)
        self.Dev1_Ch3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch3.setObjectName("Dev1_Ch3")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.Dev1_Ch3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.Dev1_Ch3_S1 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S1.setObjectName("Dev1_Ch3_S1")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S1, 0, 0, 1, 1)
        self.Dev1_Ch3_S2 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S2.setObjectName("Dev1_Ch3_S2")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S2, 0, 1, 1, 1)
        self.Dev1_Ch3_S3 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S3.setObjectName("Dev1_Ch3_S3")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S3, 1, 0, 1, 1)
        self.Dev1_Ch3_S4 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S4.setObjectName("Dev1_Ch3_S4")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch3)
        self.Dev1_Ch4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch4.setObjectName("Dev1_Ch4")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.Dev1_Ch4)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.Dev1_Ch4_S1 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S1.setObjectName("Dev1_Ch4_S1")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S1, 0, 0, 1, 1)
        self.Dev1_Ch4_S2 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S2.setObjectName("Dev1_Ch4_S2")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S2, 0, 1, 1, 1)
        self.Dev1_Ch4_S3 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S3.setObjectName("Dev1_Ch4_S3")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S3, 1, 0, 1, 1)
        self.Dev1_Ch4_S4 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S4.setObjectName("Dev1_Ch4_S4")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.dev1_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.dev1_scrollarea)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.DevLayout.addWidget(self.groupBox_dev1)
        self.groupBox_dev2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_dev2.setObjectName("groupBox_dev2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_dev2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.DeviceComboBox2 = QtWidgets.QComboBox(self.groupBox_dev2)
        self.DeviceComboBox2.setObjectName("DeviceComboBox2")
        self.DeviceComboBox2.addItem("")
        self.DeviceComboBox2.addItem("")
        self.gridLayout_5.addWidget(self.DeviceComboBox2, 0, 0, 1, 1)
        self.ConnectDevButton2 = QtWidgets.QPushButton(self.groupBox_dev2)
        self.ConnectDevButton2.setMinimumSize(QtCore.QSize(90, 0))
        self.ConnectDevButton2.setObjectName("ConnectDevButton2")
        self.gridLayout_5.addWidget(self.ConnectDevButton2, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_dev2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(120, 0))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radio_dev2_ch1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_dev2_ch1.setObjectName("radio_dev2_ch1")
        self.verticalLayout_3.addWidget(self.radio_dev2_ch1)
        self.radio_dev2_ch2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_dev2_ch2.setObjectName("radio_dev2_ch2")
        self.verticalLayout_3.addWidget(self.radio_dev2_ch2)
        self.radio_dev2_ch3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_dev2_ch3.setObjectName("radio_dev2_ch3")
        self.verticalLayout_3.addWidget(self.radio_dev2_ch3)
        self.radio_dev2_ch4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radio_dev2_ch4.setObjectName("radio_dev2_ch4")
        self.verticalLayout_3.addWidget(self.radio_dev2_ch4)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.groupBox_dev2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.dev2_scrollarea = QtWidgets.QScrollArea(self.groupBox_dev2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev2_scrollarea.sizePolicy().hasHeightForWidth())
        self.dev2_scrollarea.setSizePolicy(sizePolicy)
        self.dev2_scrollarea.setMinimumSize(QtCore.QSize(240, 0))
        self.dev2_scrollarea.setWidgetResizable(True)
        self.dev2_scrollarea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dev2_scrollarea.setObjectName("dev2_scrollarea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 223, 386))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Dev2_Ch1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch1.setObjectName("Dev2_Ch1")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.Dev2_Ch1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Dev2_Ch1_S1 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S1.setObjectName("Dev2_Ch1_S1")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S1, 0, 0, 1, 1)
        self.Dev2_Ch1_S2 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S2.setObjectName("Dev2_Ch1_S2")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S2, 0, 1, 1, 1)
        self.Dev2_Ch1_S3 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S3.setObjectName("Dev2_Ch1_S3")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S3, 1, 0, 1, 1)
        self.Dev2_Ch1_S4 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S4.setObjectName("Dev2_Ch1_S4")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch1)
        self.Dev2_Ch2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch2.setObjectName("Dev2_Ch2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.Dev2_Ch2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.Dev2_Ch2_S2 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S2.setObjectName("Dev2_Ch2_S2")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S2, 0, 1, 1, 1)
        self.Dev2_Ch2_S3 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S3.setObjectName("Dev2_Ch2_S3")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S3, 1, 0, 1, 1)
        self.Dev2_Ch2_S1 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S1.setObjectName("Dev2_Ch2_S1")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S1, 0, 0, 1, 1)
        self.Dev2_Ch2_S4 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S4.setObjectName("Dev2_Ch2_S4")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch2)
        self.Dev2_Ch3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch3.setObjectName("Dev2_Ch3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.Dev2_Ch3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.Dev2_Ch3_S1 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S1.setObjectName("Dev2_Ch3_S1")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S1, 0, 0, 1, 1)
        self.Dev2_Ch3_S3 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S3.setObjectName("Dev2_Ch3_S3")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S3, 1, 0, 1, 1)
        self.Dev2_Ch3_S4 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S4.setObjectName("Dev2_Ch3_S4")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S4, 1, 1, 1, 1)
        self.Dev2_Ch3_S2 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S2.setObjectName("Dev2_Ch3_S2")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch3)
        self.Dev2_Ch4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch4.setObjectName("Dev2_Ch4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.Dev2_Ch4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Dev2_Ch4_S1 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S1.setObjectName("Dev2_Ch4_S1")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S1, 0, 0, 1, 1)
        self.Dev2_Ch4_S2 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S2.setObjectName("Dev2_Ch4_S2")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S2, 0, 1, 1, 1)
        self.Dev2_Ch4_S3 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S3.setObjectName("Dev2_Ch4_S3")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S3, 1, 0, 1, 1)
        self.Dev2_Ch4_S4 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S4.setObjectName("Dev2_Ch4_S4")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.dev2_scrollarea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.dev2_scrollarea)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.DevLayout.addWidget(self.groupBox_dev2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.DevLayout.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.DevLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menu = QtWidgets.QMenuBar(MainWindow)
        self.menu.setGeometry(QtCore.QRect(0, 0, 1100, 27))
        self.menu.setObjectName("menu")
        self.file = QtWidgets.QMenu(self.menu)
        self.file.setObjectName("file")
        self.help = QtWidgets.QMenu(self.menu)
        self.help.setObjectName("help")
        self.tools = QtWidgets.QMenu(self.menu)
        self.tools.setObjectName("tools")
        MainWindow.setMenuBar(self.menu)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.actionLog_console = QtWidgets.QAction(MainWindow)
        self.actionLog_console.setCheckable(True)
        self.actionLog_console.setObjectName("actionLog_console")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFPGA_sensor_callibrator = QtWidgets.QAction(MainWindow)
        self.actionFPGA_sensor_callibrator.setEnabled(False)
        self.actionFPGA_sensor_callibrator.setObjectName("actionFPGA_sensor_callibrator")
        self.actionDevice_manager = QtWidgets.QAction(MainWindow)
        self.actionDevice_manager.setCheckable(True)
        self.actionDevice_manager.setObjectName("actionDevice_manager")
        self.device_manager = QtWidgets.QAction(MainWindow)
        self.device_manager.setObjectName("device_manager")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.fpga_calibration = QtWidgets.QAction(MainWindow)
        self.fpga_calibration.setObjectName("fpga_calibration")
        self.file.addAction(self.exit)
        self.help.addAction(self.actionAbout)
        self.tools.addAction(self.device_manager)
        self.tools.addAction(self.fpga_calibration)
        self.menu.addAction(self.file.menuAction())
        self.menu.addAction(self.tools.menuAction())
        self.menu.addAction(self.help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Frequency-meter application"))
        self.groupBox.setTitle(_translate("MainWindow", "Log messages:"))
        self.WarnCheck.setText(_translate("MainWindow", "Warning"))
        self.InfoCheck.setText(_translate("MainWindow", "Info"))
        self.ErrorCheck.setText(_translate("MainWindow", "Error"))
        self.DebugCheck.setText(_translate("MainWindow", "Debug"))
        self.measurement_groupBox.setTitle(_translate("MainWindow", "Measurements"))
        self.TimesgroupBox.setTitle(_translate("MainWindow", "Instrument times"))
        self.label_4.setText(_translate("MainWindow", "Fetch time:"))
        self.label.setText(_translate("MainWindow", "(s)"))
        self.label_3.setText(_translate("MainWindow", "Sample time:"))
        self.label_2.setText(_translate("MainWindow", "(s)"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.scrollcheckBox.setText(_translate("MainWindow", "Autoscroll"))
        self.groupBox_dev1.setTitle(_translate("MainWindow", "Device 1"))
        self.DeviceComboBox1.setItemText(0, _translate("MainWindow", "<None>"))
        self.DeviceComboBox1.setItemText(1, _translate("MainWindow", "DE1_SoC"))
        self.ConnectDevButton1.setText(_translate("MainWindow", "Connect"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Channels"))
        self.radio_dev1_ch1.setText(_translate("MainWindow", "RadioButton"))
        self.radio_dev1_ch2.setText(_translate("MainWindow", "RadioButton"))
        self.radio_dev1_ch3.setText(_translate("MainWindow", "RadioButton"))
        self.radio_dev1_ch4.setText(_translate("MainWindow", "RadioButton"))
        self.label_6.setText(_translate("MainWindow", "Signals"))
        self.Dev1_Ch1.setTitle(_translate("MainWindow", "Ch 1"))
        self.Dev1_Ch1_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch1_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch1_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch1_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2.setTitle(_translate("MainWindow", "Ch 2"))
        self.Dev1_Ch2_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3.setTitle(_translate("MainWindow", "Ch 3"))
        self.Dev1_Ch3_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4.setTitle(_translate("MainWindow", "Ch 4"))
        self.Dev1_Ch4_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4_S4.setText(_translate("MainWindow", "Fine"))
        self.groupBox_dev2.setTitle(_translate("MainWindow", "Device 2"))
        self.DeviceComboBox2.setItemText(0, _translate("MainWindow", "<None>"))
        self.DeviceComboBox2.setItemText(1, _translate("MainWindow", "DE1_SoC"))
        self.ConnectDevButton2.setText(_translate("MainWindow", "Connect"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Channels"))
        self.radio_dev2_ch1.setText(_translate("MainWindow", "RadioButton"))
        self.radio_dev2_ch2.setText(_translate("MainWindow", "RadioButton"))
        self.radio_dev2_ch3.setText(_translate("MainWindow", "RadioButton"))
        self.radio_dev2_ch4.setText(_translate("MainWindow", "RadioButton"))
        self.label_7.setText(_translate("MainWindow", "Signals"))
        self.Dev2_Ch1.setTitle(_translate("MainWindow", "Ch 1"))
        self.Dev2_Ch1_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch1_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch1_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch1_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2.setTitle(_translate("MainWindow", "Ch 2"))
        self.Dev2_Ch2_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3.setTitle(_translate("MainWindow", "Ch 3"))
        self.Dev2_Ch3_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4.setTitle(_translate("MainWindow", "Ch 4"))
        self.Dev2_Ch4_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4_S4.setText(_translate("MainWindow", "Fine"))
        self.file.setTitle(_translate("MainWindow", "File"))
        self.help.setTitle(_translate("MainWindow", "Help"))
        self.tools.setTitle(_translate("MainWindow", "Tools"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.exit.setText(_translate("MainWindow", "Quit"))
        self.actionLog_console.setText(_translate("MainWindow", "Log messages"))
        self.actionAbout.setText(_translate("MainWindow", "About ..."))
        self.actionFPGA_sensor_callibrator.setText(_translate("MainWindow", "FPGA sensor callibrator"))
        self.actionDevice_manager.setText(_translate("MainWindow", "Device manager"))
        self.device_manager.setText(_translate("MainWindow", "Device manager"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.fpga_calibration.setText(_translate("MainWindow", "FPGA frequency meter calibration"))

