# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/resources/interface.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 874)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.WarnCheck = QtWidgets.QRadioButton(self.groupBox)
        self.WarnCheck.setChecked(True)
        self.WarnCheck.setAutoExclusive(False)
        self.WarnCheck.setObjectName("WarnCheck")
        self.gridLayout_3.addWidget(self.WarnCheck, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 4, 1, 1)
        self.LoggerBrowser = QtWidgets.QTextBrowser(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LoggerBrowser.setFont(font)
        self.LoggerBrowser.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.LoggerBrowser.setAutoFillBackground(False)
        self.LoggerBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.LoggerBrowser.setObjectName("LoggerBrowser")
        self.gridLayout_3.addWidget(self.LoggerBrowser, 2, 0, 2, 5)
        self.InfoCheck = QtWidgets.QRadioButton(self.groupBox)
        self.InfoCheck.setChecked(True)
        self.InfoCheck.setAutoExclusive(False)
        self.InfoCheck.setObjectName("InfoCheck")
        self.gridLayout_3.addWidget(self.InfoCheck, 1, 0, 1, 1)
        self.ErrorCheck = QtWidgets.QRadioButton(self.groupBox)
        self.ErrorCheck.setChecked(True)
        self.ErrorCheck.setAutoExclusive(False)
        self.ErrorCheck.setObjectName("ErrorCheck")
        self.gridLayout_3.addWidget(self.ErrorCheck, 1, 2, 1, 1)
        self.DebugCheck = QtWidgets.QRadioButton(self.groupBox)
        self.DebugCheck.setEnabled(True)
        self.DebugCheck.setAutoExclusive(False)
        self.DebugCheck.setObjectName("DebugCheck")
        self.gridLayout_3.addWidget(self.DebugCheck, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 4)
        self.groupBox_dev = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_dev.setObjectName("groupBox_dev")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_dev)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_dev1 = QtWidgets.QGroupBox(self.groupBox_dev)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_dev1.sizePolicy().hasHeightForWidth())
        self.groupBox_dev1.setSizePolicy(sizePolicy)
        self.groupBox_dev1.setObjectName("groupBox_dev1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_dev1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.connected_label_1 = QtWidgets.QLabel(self.groupBox_dev1)
        self.connected_label_1.setObjectName("connected_label_1")
        self.gridLayout_4.addWidget(self.connected_label_1, 1, 2, 1, 1)
        self.DeviceComboBox = QtWidgets.QComboBox(self.groupBox_dev1)
        self.DeviceComboBox.setObjectName("DeviceComboBox")
        self.DeviceComboBox.addItem("")
        self.DeviceComboBox.addItem("")
        self.gridLayout_4.addWidget(self.DeviceComboBox, 0, 0, 1, 1)
        self.devname_label_r_1 = QtWidgets.QLabel(self.groupBox_dev1)
        self.devname_label_r_1.setObjectName("devname_label_r_1")
        self.gridLayout_4.addWidget(self.devname_label_r_1, 0, 2, 1, 1)
        self.removeButton_1 = QtWidgets.QPushButton(self.groupBox_dev1)
        self.removeButton_1.setEnabled(False)
        self.removeButton_1.setObjectName("removeButton_1")
        self.gridLayout_4.addWidget(self.removeButton_1, 2, 0, 1, 1)
        self.devname_label_l_1 = QtWidgets.QLabel(self.groupBox_dev1)
        self.devname_label_l_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.devname_label_l_1.setObjectName("devname_label_l_1")
        self.gridLayout_4.addWidget(self.devname_label_l_1, 0, 1, 1, 1)
        self.LoadDeviceButton = QtWidgets.QPushButton(self.groupBox_dev1)
        self.LoadDeviceButton.setObjectName("LoadDeviceButton")
        self.gridLayout_4.addWidget(self.LoadDeviceButton, 1, 0, 1, 1)
        self.status_label_1 = QtWidgets.QLabel(self.groupBox_dev1)
        self.status_label_1.setEnabled(True)
        self.status_label_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_label_1.setObjectName("status_label_1")
        self.gridLayout_4.addWidget(self.status_label_1, 1, 1, 1, 1)
        self.connectButton_1 = QtWidgets.QPushButton(self.groupBox_dev1)
        self.connectButton_1.setEnabled(False)
        self.connectButton_1.setObjectName("connectButton_1")
        self.gridLayout_4.addWidget(self.connectButton_1, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_4)
        self.dev1_scrollarea = QtWidgets.QScrollArea(self.groupBox_dev1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev1_scrollarea.sizePolicy().hasHeightForWidth())
        self.dev1_scrollarea.setSizePolicy(sizePolicy)
        self.dev1_scrollarea.setMinimumSize(QtCore.QSize(240, 80))
        self.dev1_scrollarea.setWidgetResizable(True)
        self.dev1_scrollarea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dev1_scrollarea.setObjectName("dev1_scrollarea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -24, 221, 334))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Dev1_Ch1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch1.setObjectName("Dev1_Ch1")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.Dev1_Ch1)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.Dev1_Ch1_S1 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S1.setObjectName("Dev1_Ch1_S1")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S1, 0, 0, 1, 1)
        self.Dev1_Ch1_S2 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S2.setObjectName("Dev1_Ch1_S2")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S2, 0, 1, 1, 1)
        self.Dev1_Ch1_S3 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S3.setObjectName("Dev1_Ch1_S3")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S3, 1, 0, 1, 1)
        self.Dev1_Ch1_S4 = QtWidgets.QCheckBox(self.Dev1_Ch1)
        self.Dev1_Ch1_S4.setObjectName("Dev1_Ch1_S4")
        self.gridLayout_18.addWidget(self.Dev1_Ch1_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch1)
        self.Dev1_Ch2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch2.setObjectName("Dev1_Ch2")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.Dev1_Ch2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.Dev1_Ch2_S1 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S1.setObjectName("Dev1_Ch2_S1")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S1, 0, 0, 1, 1)
        self.Dev1_Ch2_S2 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S2.setObjectName("Dev1_Ch2_S2")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S2, 0, 1, 1, 1)
        self.Dev1_Ch2_S3 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S3.setObjectName("Dev1_Ch2_S3")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S3, 1, 0, 1, 1)
        self.Dev1_Ch2_S4 = QtWidgets.QCheckBox(self.Dev1_Ch2)
        self.Dev1_Ch2_S4.setObjectName("Dev1_Ch2_S4")
        self.gridLayout_19.addWidget(self.Dev1_Ch2_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch2)
        self.Dev1_Ch3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch3.setObjectName("Dev1_Ch3")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.Dev1_Ch3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.Dev1_Ch3_S1 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S1.setObjectName("Dev1_Ch3_S1")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S1, 0, 0, 1, 1)
        self.Dev1_Ch3_S2 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S2.setObjectName("Dev1_Ch3_S2")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S2, 0, 1, 1, 1)
        self.Dev1_Ch3_S3 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S3.setObjectName("Dev1_Ch3_S3")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S3, 1, 0, 1, 1)
        self.Dev1_Ch3_S4 = QtWidgets.QCheckBox(self.Dev1_Ch3)
        self.Dev1_Ch3_S4.setObjectName("Dev1_Ch3_S4")
        self.gridLayout_20.addWidget(self.Dev1_Ch3_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch3)
        self.Dev1_Ch4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.Dev1_Ch4.setObjectName("Dev1_Ch4")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.Dev1_Ch4)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.Dev1_Ch4_S1 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S1.setObjectName("Dev1_Ch4_S1")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S1, 0, 0, 1, 1)
        self.Dev1_Ch4_S2 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S2.setObjectName("Dev1_Ch4_S2")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S2, 0, 1, 1, 1)
        self.Dev1_Ch4_S3 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S3.setObjectName("Dev1_Ch4_S3")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S3, 1, 0, 1, 1)
        self.Dev1_Ch4_S4 = QtWidgets.QCheckBox(self.Dev1_Ch4)
        self.Dev1_Ch4_S4.setObjectName("Dev1_Ch4_S4")
        self.gridLayout_21.addWidget(self.Dev1_Ch4_S4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.Dev1_Ch4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.dev1_scrollarea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.dev1_scrollarea)
        self.horizontalLayout.addWidget(self.groupBox_dev1)
        self.groupBox_dev2 = QtWidgets.QGroupBox(self.groupBox_dev)
        self.groupBox_dev2.setObjectName("groupBox_dev2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_dev2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.DeviceComboBox_2 = QtWidgets.QComboBox(self.groupBox_dev2)
        self.DeviceComboBox_2.setObjectName("DeviceComboBox_2")
        self.DeviceComboBox_2.addItem("")
        self.DeviceComboBox_2.addItem("")
        self.gridLayout_5.addWidget(self.DeviceComboBox_2, 0, 0, 1, 1)
        self.devname_label_r_2 = QtWidgets.QLabel(self.groupBox_dev2)
        self.devname_label_r_2.setObjectName("devname_label_r_2")
        self.gridLayout_5.addWidget(self.devname_label_r_2, 0, 2, 1, 1)
        self.LoadDeviceButton_2 = QtWidgets.QPushButton(self.groupBox_dev2)
        self.LoadDeviceButton_2.setObjectName("LoadDeviceButton_2")
        self.gridLayout_5.addWidget(self.LoadDeviceButton_2, 1, 0, 1, 1)
        self.connectButton_2 = QtWidgets.QPushButton(self.groupBox_dev2)
        self.connectButton_2.setEnabled(False)
        self.connectButton_2.setObjectName("connectButton_2")
        self.gridLayout_5.addWidget(self.connectButton_2, 2, 2, 1, 1)
        self.removeButton_2 = QtWidgets.QPushButton(self.groupBox_dev2)
        self.removeButton_2.setEnabled(False)
        self.removeButton_2.setObjectName("removeButton_2")
        self.gridLayout_5.addWidget(self.removeButton_2, 2, 0, 1, 1)
        self.status_label_2 = QtWidgets.QLabel(self.groupBox_dev2)
        self.status_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status_label_2.setObjectName("status_label_2")
        self.gridLayout_5.addWidget(self.status_label_2, 1, 1, 1, 1)
        self.devname_label_l_2 = QtWidgets.QLabel(self.groupBox_dev2)
        self.devname_label_l_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.devname_label_l_2.setObjectName("devname_label_l_2")
        self.gridLayout_5.addWidget(self.devname_label_l_2, 0, 1, 1, 1)
        self.connected_label_2 = QtWidgets.QLabel(self.groupBox_dev2)
        self.connected_label_2.setObjectName("connected_label_2")
        self.gridLayout_5.addWidget(self.connected_label_2, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_5)
        self.dev2_scrollarea = QtWidgets.QScrollArea(self.groupBox_dev2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dev2_scrollarea.sizePolicy().hasHeightForWidth())
        self.dev2_scrollarea.setSizePolicy(sizePolicy)
        self.dev2_scrollarea.setMinimumSize(QtCore.QSize(240, 0))
        self.dev2_scrollarea.setWidgetResizable(True)
        self.dev2_scrollarea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dev2_scrollarea.setObjectName("dev2_scrollarea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -24, 221, 334))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Dev2_Ch1 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch1.setObjectName("Dev2_Ch1")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.Dev2_Ch1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.Dev2_Ch1_S1 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S1.setObjectName("Dev2_Ch1_S1")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S1, 0, 0, 1, 1)
        self.Dev2_Ch1_S2 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S2.setObjectName("Dev2_Ch1_S2")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S2, 0, 1, 1, 1)
        self.Dev2_Ch1_S3 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S3.setObjectName("Dev2_Ch1_S3")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S3, 1, 0, 1, 1)
        self.Dev2_Ch1_S4 = QtWidgets.QCheckBox(self.Dev2_Ch1)
        self.Dev2_Ch1_S4.setObjectName("Dev2_Ch1_S4")
        self.gridLayout_15.addWidget(self.Dev2_Ch1_S4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch1)
        self.Dev2_Ch2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch2.setObjectName("Dev2_Ch2")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.Dev2_Ch2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.Dev2_Ch2_S2 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S2.setObjectName("Dev2_Ch2_S2")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S2, 0, 1, 1, 1)
        self.Dev2_Ch2_S3 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S3.setObjectName("Dev2_Ch2_S3")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S3, 1, 0, 1, 1)
        self.Dev2_Ch2_S1 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S1.setObjectName("Dev2_Ch2_S1")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S1, 0, 0, 1, 1)
        self.Dev2_Ch2_S4 = QtWidgets.QCheckBox(self.Dev2_Ch2)
        self.Dev2_Ch2_S4.setObjectName("Dev2_Ch2_S4")
        self.gridLayout_16.addWidget(self.Dev2_Ch2_S4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch2)
        self.Dev2_Ch3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch3.setObjectName("Dev2_Ch3")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.Dev2_Ch3)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.Dev2_Ch3_S1 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S1.setObjectName("Dev2_Ch3_S1")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S1, 0, 0, 1, 1)
        self.Dev2_Ch3_S3 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S3.setObjectName("Dev2_Ch3_S3")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S3, 1, 0, 1, 1)
        self.Dev2_Ch3_S4 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S4.setObjectName("Dev2_Ch3_S4")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S4, 1, 1, 1, 1)
        self.Dev2_Ch3_S2 = QtWidgets.QCheckBox(self.Dev2_Ch3)
        self.Dev2_Ch3_S2.setObjectName("Dev2_Ch3_S2")
        self.gridLayout_17.addWidget(self.Dev2_Ch3_S2, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch3)
        self.Dev2_Ch4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.Dev2_Ch4.setObjectName("Dev2_Ch4")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.Dev2_Ch4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.Dev2_Ch4_S1 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S1.setObjectName("Dev2_Ch4_S1")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S1, 0, 0, 1, 1)
        self.Dev2_Ch4_S2 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S2.setObjectName("Dev2_Ch4_S2")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S2, 0, 1, 1, 1)
        self.Dev2_Ch4_S3 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S3.setObjectName("Dev2_Ch4_S3")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S3, 1, 0, 1, 1)
        self.Dev2_Ch4_S4 = QtWidgets.QCheckBox(self.Dev2_Ch4)
        self.Dev2_Ch4_S4.setObjectName("Dev2_Ch4_S4")
        self.gridLayout_14.addWidget(self.Dev2_Ch4_S4, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.Dev2_Ch4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.dev2_scrollarea.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_3.addWidget(self.dev2_scrollarea)
        self.horizontalLayout.addWidget(self.groupBox_dev2)
        self.gridLayout.addWidget(self.groupBox_dev, 0, 0, 1, 4)
        self.measurement_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.measurement_groupBox.setObjectName("measurement_groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.measurement_groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.TimesgroupBox = QtWidgets.QGroupBox(self.measurement_groupBox)
        self.TimesgroupBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TimesgroupBox.sizePolicy().hasHeightForWidth())
        self.TimesgroupBox.setSizePolicy(sizePolicy)
        self.TimesgroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TimesgroupBox.setObjectName("TimesgroupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.TimesgroupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.TimesgroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)
        self.SampleTimeBox = QtWidgets.QDoubleSpinBox(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SampleTimeBox.sizePolicy().hasHeightForWidth())
        self.SampleTimeBox.setSizePolicy(sizePolicy)
        self.SampleTimeBox.setAccelerated(True)
        self.SampleTimeBox.setDecimals(3)
        self.SampleTimeBox.setMinimum(0.001)
        self.SampleTimeBox.setMaximum(20.0)
        self.SampleTimeBox.setSingleStep(0.001)
        self.SampleTimeBox.setProperty("value", 1.0)
        self.SampleTimeBox.setObjectName("SampleTimeBox")
        self.gridLayout_8.addWidget(self.SampleTimeBox, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.TimesgroupBox)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 1, 1, 1, 1)
        self.FetchTimeBox = QtWidgets.QDoubleSpinBox(self.TimesgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FetchTimeBox.sizePolicy().hasHeightForWidth())
        self.FetchTimeBox.setSizePolicy(sizePolicy)
        self.FetchTimeBox.setAccelerated(True)
        self.FetchTimeBox.setDecimals(3)
        self.FetchTimeBox.setMinimum(0.001)
        self.FetchTimeBox.setMaximum(20.0)
        self.FetchTimeBox.setSingleStep(0.001)
        self.FetchTimeBox.setProperty("value", 1.0)
        self.FetchTimeBox.setObjectName("FetchTimeBox")
        self.gridLayout_8.addWidget(self.FetchTimeBox, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.TimesgroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.TimesgroupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.TimesgroupBox, 3, 0, 2, 1)
        self.StartButton = QtWidgets.QPushButton(self.measurement_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartButton.sizePolicy().hasHeightForWidth())
        self.StartButton.setSizePolicy(sizePolicy)
        self.StartButton.setMinimumSize(QtCore.QSize(250, 0))
        self.StartButton.setObjectName("StartButton")
        self.gridLayout_7.addWidget(self.StartButton, 0, 0, 1, 1)
        self.plotVLayout = QtWidgets.QVBoxLayout()
        self.plotVLayout.setObjectName("plotVLayout")
        self.gridLayout_7.addLayout(self.plotVLayout, 0, 2, 8, 4)
        self.DebugButton = QtWidgets.QPushButton(self.measurement_groupBox)
        self.DebugButton.setObjectName("DebugButton")
        self.gridLayout_7.addWidget(self.DebugButton, 6, 0, 1, 1)
        self.SaveButton = QtWidgets.QPushButton(self.measurement_groupBox)
        self.SaveButton.setObjectName("SaveButton")
        self.gridLayout_7.addWidget(self.SaveButton, 2, 0, 1, 1)
        self.StopButton = QtWidgets.QPushButton(self.measurement_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopButton.sizePolicy().hasHeightForWidth())
        self.StopButton.setSizePolicy(sizePolicy)
        self.StopButton.setMinimumSize(QtCore.QSize(250, 0))
        self.StopButton.setObjectName("StopButton")
        self.gridLayout_7.addWidget(self.StopButton, 1, 0, 1, 1)
        self.scrollcheckBox = QtWidgets.QCheckBox(self.measurement_groupBox)
        self.scrollcheckBox.setChecked(True)
        self.scrollcheckBox.setObjectName("scrollcheckBox")
        self.gridLayout_7.addWidget(self.scrollcheckBox, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.measurement_groupBox, 1, 0, 3, 4)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menuBar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLog_console = QtWidgets.QAction(MainWindow)
        self.actionLog_console.setCheckable(True)
        self.actionLog_console.setObjectName("actionLog_console")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionFPGA_sensor_callibrator = QtWidgets.QAction(MainWindow)
        self.actionFPGA_sensor_callibrator.setEnabled(False)
        self.actionFPGA_sensor_callibrator.setObjectName("actionFPGA_sensor_callibrator")
        self.actionDevice_manager = QtWidgets.QAction(MainWindow)
        self.actionDevice_manager.setCheckable(True)
        self.actionDevice_manager.setObjectName("actionDevice_manager")
        self.actionDevice_Manager = QtWidgets.QAction(MainWindow)
        self.actionDevice_Manager.setObjectName("actionDevice_Manager")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        self.actionEdit.setObjectName("actionEdit")
        self.actionFPGAcalibration = QtWidgets.QAction(MainWindow)
        self.actionFPGAcalibration.setObjectName("actionFPGAcalibration")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuTools.addAction(self.actionDevice_Manager)
        self.menuTools.addAction(self.actionFPGAcalibration)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Frequency-meter application"))
        self.groupBox.setTitle(_translate("MainWindow", "Log messages:"))
        self.WarnCheck.setText(_translate("MainWindow", "Warning"))
        self.InfoCheck.setText(_translate("MainWindow", "Info"))
        self.ErrorCheck.setText(_translate("MainWindow", "Error"))
        self.DebugCheck.setText(_translate("MainWindow", "Debug"))
        self.groupBox_dev.setTitle(_translate("MainWindow", "Devices"))
        self.groupBox_dev1.setTitle(_translate("MainWindow", "Device 1"))
        self.connected_label_1.setText(_translate("MainWindow", "connected"))
        self.DeviceComboBox.setItemText(0, _translate("MainWindow", "<None>"))
        self.DeviceComboBox.setItemText(1, _translate("MainWindow", "DE1_SoC"))
        self.devname_label_r_1.setText(_translate("MainWindow", "dev1name"))
        self.removeButton_1.setText(_translate("MainWindow", "Remove device"))
        self.devname_label_l_1.setText(_translate("MainWindow", "Name:"))
        self.LoadDeviceButton.setText(_translate("MainWindow", "Load device"))
        self.status_label_1.setText(_translate("MainWindow", "Status:"))
        self.connectButton_1.setText(_translate("MainWindow", "Connect"))
        self.Dev1_Ch1.setTitle(_translate("MainWindow", "Ch 1"))
        self.Dev1_Ch1_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch1_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch1_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch1_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2.setTitle(_translate("MainWindow", "Ch 2"))
        self.Dev1_Ch2_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch2_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3.setTitle(_translate("MainWindow", "Ch 3"))
        self.Dev1_Ch3_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch3_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4.setTitle(_translate("MainWindow", "Ch 4"))
        self.Dev1_Ch4_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev1_Ch4_S4.setText(_translate("MainWindow", "Fine"))
        self.groupBox_dev2.setTitle(_translate("MainWindow", "Device 2"))
        self.DeviceComboBox_2.setItemText(0, _translate("MainWindow", "<None>"))
        self.DeviceComboBox_2.setItemText(1, _translate("MainWindow", "DE1_SoC"))
        self.devname_label_r_2.setText(_translate("MainWindow", "dev2name"))
        self.LoadDeviceButton_2.setText(_translate("MainWindow", "Load device"))
        self.connectButton_2.setText(_translate("MainWindow", "Connect"))
        self.removeButton_2.setText(_translate("MainWindow", "Remove device"))
        self.status_label_2.setText(_translate("MainWindow", "Status:"))
        self.devname_label_l_2.setText(_translate("MainWindow", "Name:"))
        self.connected_label_2.setText(_translate("MainWindow", "connected"))
        self.Dev2_Ch1.setTitle(_translate("MainWindow", "Ch 1"))
        self.Dev2_Ch1_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch1_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch1_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch1_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2.setTitle(_translate("MainWindow", "Ch 2"))
        self.Dev2_Ch2_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch2_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3.setTitle(_translate("MainWindow", "Ch 3"))
        self.Dev2_Ch3_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3_S4.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch3_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4.setTitle(_translate("MainWindow", "Ch 4"))
        self.Dev2_Ch4_S1.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4_S2.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4_S3.setText(_translate("MainWindow", "Fine"))
        self.Dev2_Ch4_S4.setText(_translate("MainWindow", "Fine"))
        self.measurement_groupBox.setTitle(_translate("MainWindow", "Measurements"))
        self.TimesgroupBox.setTitle(_translate("MainWindow", "Instrument times"))
        self.label_3.setText(_translate("MainWindow", "Sample time:"))
        self.label.setText(_translate("MainWindow", "(s)"))
        self.label_2.setText(_translate("MainWindow", "(s)"))
        self.label_4.setText(_translate("MainWindow", "Fetch time:"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.DebugButton.setText(_translate("MainWindow", "Debug"))
        self.SaveButton.setText(_translate("MainWindow", "Save"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.scrollcheckBox.setText(_translate("MainWindow", "Autoscroll"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionLog_console.setText(_translate("MainWindow", "Log messages"))
        self.actionAbout.setText(_translate("MainWindow", "About ..."))
        self.actionFPGA_sensor_callibrator.setText(_translate("MainWindow", "FPGA sensor callibrator"))
        self.actionDevice_manager.setText(_translate("MainWindow", "Device manager"))
        self.actionDevice_Manager.setText(_translate("MainWindow", "Device manager"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionFPGAcalibration.setText(_translate("MainWindow", "FPGA frequency meter calibration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

